// Generated by CoffeeScript 1.8.0
(function() {
  var Maze, Piece, maze;

  Piece = (function() {
    function Piece(col, row, id, element) {
      this.col = col;
      this.row = row;
      this.id = id;
      this.element = element;
    }

    return Piece;

  })();

  Maze = (function() {
    function Maze(pieces, blankCol, blankRow) {
      this.pieces = pieces != null ? pieces : [];
      this.blankCol = blankCol != null ? blankCol : 4;
      this.blankRow = blankRow != null ? blankRow : 4;
    }

    Maze.prototype.push = function(piece) {
      return this.pieces.push(piece);
    };

    Maze.prototype.initialize = function() {
      this.initializeDataStructure();
      this.initializePieceElement();
      return this.updatePosition();
    };

    Maze.prototype.initializeDataStructure = function() {
      var col, ele, onePiece, piece, pieces, row, that, _results;
      col = 1;
      pieces = document.getElementById('puzzlearea').getElementsByTagName('div');
      _results = [];
      while (col < 5) {
        row = 1;
        while (row < 5) {
          piece = new Piece(col, row, (col - 1) * 4 + row, pieces[(col - 1) * 4 + row - 1]);
          if (piece.element !== void 0) {
            this.push(piece);
            onePiece = this.pieces[(col - 1) * 4 + row - 1];
            that = this;
            ele = onePiece.element;
            onePiece.element.onclick = function(ele) {
              return function() {
                return that.pieceClickHandler(ele);
              };
            }(ele);
          }
          row++;
        }
        _results.push(col++);
      }
      return _results;
    };

    Maze.prototype.initializePieceElement = function() {
      var piece, _i, _len, _ref, _results;
      _ref = this.pieces;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        piece = _ref[_i];
        if (piece.element !== void 0) {
          _results.push(piece.element.style.backgroundPosition = -(piece.row - 1) * 96 + "px " + -(piece.col - 1) * 96 + "px");
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Maze.prototype.updatePosition = function() {
      var piece, _i, _len, _ref, _results;
      _ref = this.pieces;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        piece = _ref[_i];
        if (piece.element !== void 0) {
          piece.element.style.left = (piece.row - 1) * 96 + "px";
          piece.element.style.top = (piece.col - 1) * 96 + "px";
          if (Math.abs(piece.row - this.blankRow) + Math.abs(piece.col - this.blankCol) > 1) {
            _results.push(piece.element.className = 'puzzlepiece');
          } else {
            _results.push(piece.element.className = 'puzzlepiece movablepiece');
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Maze.prototype.pieceClickHandler = function(ele) {
      var index;
      console.log(ele);
      index = parseInt(ele.textContent);
      if (Math.abs(this.pieces[index - 1].row - this.blankRow) + Math.abs(this.pieces[index - 1].col - this.blankCol) <= 1) {
        this.move(index);
        this.updatePosition();
        if (this.completed()) {
          alert('You Win!');
          return this.shuffle();
        }
      }
    };

    Maze.prototype.move = function(index) {
      this.pieces[index - 1].col ^= this.blankCol;
      this.blankCol ^= this.pieces[index - 1].col;
      this.pieces[index - 1].col ^= this.blankCol;
      this.pieces[index - 1].row ^= this.blankRow;
      this.blankRow ^= this.pieces[index - 1].row;
      return this.pieces[index - 1].row ^= this.blankRow;
    };

    Maze.prototype.completed = function() {
      var index;
      index = 1;
      while (index <= 15) {
        if ((this.pieces[index - 1].col - 1) * 4 + row !== this.pieces[index - 1].id) {
          return false;
        }
        index++;
      }
      return true;
    };

    Maze.prototype.shuffle = function() {
      return alert('shuffle');
    };

    return Maze;

  })();

  maze = new Maze;

  window.onload = function() {
    return maze.initialize();
  };

}).call(this);
