// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    $('#bigger-pimpin').click(function() {
      return setInterval(function() {
        return $('textarea').css('fontSize', parseInt($('textarea').css('fontSize')) + 2 + 'pt');
      }, 500);
    });
    $('#bling').click(function() {
      $('textarea').css('text-decoration', $('#bling').attr('checked') === 'checked' ? 'underline' : 'none');
      $('textarea').css('font-weight', $('#bling').attr('checked') === 'checked' ? 'bold' : 'normal');
      $('textarea').css('color', $('#bling').attr('checked') === 'checked' ? 'green' : 'black');
      $('textarea').css('fontSize', $('#bling').attr('checked') === 'checked' ? '24pt' : '12pt');
      $('textarea').css('padding', $('#bling').attr('checked') === 'checked' ? '10px' : '0');
      return $('body').css('background-image', $('#bling').attr('checked') === 'checked' ? 'url(hundred-dollar-bill.jpg)' : 'none');
    });
    return $('#snoopify').click(function() {
      return $('textarea').val($('textarea').val().toUpperCase().split('\n').join('-izzle.\n'));
    });
  });

}).call(this);
